spring:
  application:
    name: chatbot
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chatbot?useUnicode=true
      &characterEncoding=utf8
      &useSSL=false
      &serverTimezone=Asia/Shanghai
      &allowPublicKeyRetrieval=true
      &rewriteBatchedStatements=true
    username: ${chat.datasource.username}
    password: ${chat.datasource.password}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
  data:
    redis:
      host: localhost
      port: 6379
      database: 1
      password: ${chat.redis.password}


server:
  port: 8123
  servlet:
    context-path: /api